import {Dimensions} from 'react-native';
import {ms} from 'react-native-size-matters';
// dimensions.js
export const DimensionConstants = {
  zero: ms(0),
  one: ms(1),
  two: ms(2),
  three: ms(3),
  four: ms(4),
  five: ms(5),
  six: ms(6),
  seven: ms(7),
  eight: ms(8),
  nine: ms(9),
  ten: ms(10),
  eleven: ms(11),
  twelve: ms(12),
  thirteen: ms(13),
  fourteen: ms(14),
  fifteen: ms(15),
  sixteen: ms(16),
  seventeen: ms(17),
  eighteen: ms(18),
  nineteen: ms(19),
  twenty: ms(20),
  twentyOne: ms(21),
  twentyTwo: ms(22),
  twentyThree: ms(23),
  twentyFour: ms(24),
  twentyFive: ms(25),
  twentySix: ms(26),
  twentySeven: ms(27),
  twentyEight: ms(28),
  twentyNine: ms(29),
  thirty: ms(30),
  thirtyOne: ms(31),
  thirtyTwo: ms(32),
  thirtyThree: ms(33),
  thirtyFour: ms(34),
  thirtyFive: ms(35),
  thirtySix: ms(36),
  thirtySeven: ms(37),
  thirtyEight: ms(38),
  thirtyNine: ms(39),
  forty: ms(40),
  fortyOne: ms(41),
  fortyTwo: ms(42),
  fortyThree: ms(43),
  fortyFour: ms(44),
  fortyFive: ms(45),
  fortySix: ms(46),
  fortySeven: ms(47),
  fortyEight: ms(48),
  fortyNine: ms(49),
  fifty: ms(50),
  fiftyOne: ms(51),
  fiftyTwo: ms(52),
  fiftyThree: ms(53),
  fiftyFour: ms(54),
  fiftyFive: ms(55),
  fiftySix: ms(56),
  fiftySeven: ms(57),
  fiftyEight: ms(58),
  fiftyNine: ms(59),
  sixty: ms(60),
  sixtyOne: ms(61),
  sixtyTwo: ms(62),
  sixtyThree: ms(63),
  sixtyFour: ms(64),
  sixtyFive: ms(65),
  sixtySix: ms(66),
  sixtySeven: ms(67),
  sixtyEight: ms(68),
  sixtyNine: ms(69),
  seventy: ms(70),
  seventyOne: ms(71),
  seventyTwo: ms(72),
  seventyThree: ms(73),
  seventyFour: ms(74),
  seventyFive: ms(75),
  seventySix: ms(76),
  seventySeven: ms(77),
  seventyEight: ms(78),
  seventyNine: ms(79),
  eighty: ms(80),
  eightyOne: ms(81),
  eightyTwo: ms(82),
  eightyThree: ms(83),
  eightyFour: ms(84),
  eightyFive: ms(85),
  eightySix: ms(86),
  eightySeven: ms(87),
  eightyEight: ms(88),
  eightyNine: ms(89),
  ninety: ms(90),
  ninetyOne: ms(91),
  ninetyTwo: ms(92),
  ninetyThree: ms(93),
  ninetyFour: ms(94),
  ninetyFive: ms(95),
  ninetySix: ms(96),
  ninetySeven: ms(97),
  ninetyEight: ms(98),
  ninetyNine: ms(99),
  oneHundred: ms(100),
  oneHundredThree: ms(103),
  oneHundredTen:ms(110),
  oneHundredEighteen: ms(118),
  oneHundredTwenty: ms(120),
  oneHundredTwentyFour: ms(124),
  oneHundredThirty:ms(130),
  oneHundredFortyFive :ms(145),
  oneHundredFortySeven: ms(147),
  oneHundredFifty: ms(150),
  oneHundredFiftyFour: ms(154),
  oneHundredsixty: ms(160),
  oneHundredsixtyOne:ms(161),
  oneHundredSixtyFour: ms(164),
  oneHundredSeventy: ms(170),
  oneHundredSeventyFour: ms(174),
  oneHundredEighty:ms(180),
  oneHundredEightyyFour: ms(184),

  oneHundredNintySix: ms(196),

  twoHundred: ms(200),
  twoTwenty: ms(220),
  twoFifty: ms(250),
  twoHundredNintyThree: ms(293),

  threeHundred: ms(300),
  threeHundredEleven: ms(311),

  threeTwenty: ms(320),
  threeFifty: ms(350),
  fourHundred: ms(400),
  fourFifty: ms(450),
  fiveHundred: ms(500),
  oneThusand: ms(1000),
  twoThousand: ms(2000),
  threeThousand: ms(3000),
  fourThousand: ms(4000),
  fiveThousand: ms(5000),
  tenThousand: ms(10000),
};

export const DoubleDimensionConstants = {
  zeroPointOne: ms(0.1),
  zeroPointTwo: ms(0.2),
  zeroPointThree: ms(0.3),
  zeroPointFour: ms(0.4),
  zeroPointFive: ms(0.5),
  zeroPointSix: ms(0.6),
  zeroPointSeven: ms(0.7),
  zeroPointEight: ms(0.8),
  zeroPointNine: ms(0.9),
  one: ms(1.0),
  onePointFive: ms(1.5),
  zeroPointTwoFive: ms(0.25),
  zeroPointSevenFive: ms(0.75),
};



export const {height, width} = Dimensions.get('screen');
